<?php
require_once 'db_connection.php';

// Fetch current GCash QR from settings
$gcashQr = 'https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=GCash+09123456789';
$res = $conn->query("SELECT setting_value FROM settings WHERE setting_key = 'gcash_qr' LIMIT 1");
if ($res && $row = $res->fetch_assoc()) {
    $gcashQr = htmlspecialchars($row['setting_value'], ENT_QUOTES, 'UTF-8');
}

$gcashQrModal = str_replace('200x200', '180x180', $gcashQr);
$conn->close();
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>PicklePro — Court Reservation System</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=DM+Sans:wght@300;400;500;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="style.css">
</head>
<body>

<!-- ===== NAVIGATION ===== -->
<nav class="navbar">
  <div class="nav-inner">
    <div class="nav-logo">
      <span class="logo-text">Pickle<em>Pro</em></span>
    </div>
    <div class="nav-center">
      <a href="#" class="nav-link active" data-view="booking">Book Courts</a>
      <a href="#" class="nav-link" data-view="admin">Admin Dashboard</a>
    </div>
    <div class="nav-right">
      <div class="date-picker-wrap">
        <svg class="cal-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="4" width="18" height="18" rx="2"/><line x1="16" y1="2" x2="16" y2="6"/><line x1="8" y1="2" x2="8" y2="6"/><line x1="3" y1="10" x2="21" y2="10"/></svg>
        <input type="date" id="booking_date" name="booking_date" class="date-input">
      </div>
    </div>
  </div>
</nav>

<!-- ===== BOOKING VIEW ===== -->
<div id="view-booking" class="view active">

  <div class="page-hero">
    <div class="hero-content">
      <h1 class="hero-title">Reserve Your <span class="gold-text">Court</span></h1>
      <p class="hero-sub">8 premium courts · 7AM – 10PM · Instant confirmation</p>
    </div>
    <div class="legend">
      <span class="legend-item"><span class="legend-dot available"></span>Available</span>
      <span class="legend-item"><span class="legend-dot selected"></span>Selected</span>
      <span class="legend-item"><span class="legend-dot pending"></span>Pending</span>
      <span class="legend-item"><span class="legend-dot booked"></span>Booked</span>
      <span class="legend-item"><span class="legend-dot awaiting"></span>Awaiting</span>
    </div>
  </div>

  <!-- Schedule Grid -->
  <div class="schedule-wrapper">
    <div class="schedule-scroll">
      <div class="schedule-grid" id="scheduleGrid">
        <!-- Header Row -->
        <div class="grid-header time-header">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" width="16"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>
          Time
        </div>
        <div class="grid-header court-header">Court 1</div>
        <div class="grid-header court-header">Court 2</div>
        <div class="grid-header court-header">Court 3</div>
        <div class="grid-header court-header">Court 4</div>
        <div class="grid-header court-header">Court 5</div>
        <div class="grid-header court-header">Court 6</div>
        <div class="grid-header court-header">Court 7</div>
        <div class="grid-header court-header">Court 8</div>
        <!-- Time slots generated by JS -->
      </div>
    </div>
  </div>

  <!-- Sticky Booking Bar -->
  <div class="booking-bar" id="bookingBar">
    <div class="booking-bar-inner">
      <div class="selection-summary">
        <span class="selection-count" id="selectionCount">0 slots selected</span>
        <span class="selection-detail" id="selectionDetail">Click available slots to select</span>
      </div>
      <button class="btn-confirm" id="btnConfirm" disabled>
        Confirm Booking
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" width="16"><polyline points="9 18 15 12 9 6"/></svg>
      </button>
    </div>
  </div>

</div>

<!-- ===== ADMIN VIEW ===== -->
<div id="view-admin" class="view">

  <div class="page-hero admin-hero">
    <div class="hero-content">
      <h1 class="hero-title">Admin <span class="gold-text">Dashboard</span></h1>
      <p class="hero-sub">Manage reservations, receipts & settings</p>
    </div>
    <div class="admin-tabs">
      <button class="admin-tab active" data-tab="reservations">Reservations</button>
      <button class="admin-tab" data-tab="settings">Settings</button>
    </div>
  </div>

  <!-- Reservations Tab -->
  <div class="admin-panel active" id="tab-reservations">
    <div class="table-toolbar">
      <input type="text" placeholder="Search by email or court…" class="search-input" id="adminSearch">
      <select class="filter-select" id="statusFilter">
        <option value="">All Statuses</option>
        <option value="booked">Booked</option>
        <option value="awaiting">Awaiting</option>
        <option value="pending">Pending</option>
      </select>
    </div>
    <div class="table-wrap">
      <table class="admin-table" id="adminTable">
        <thead>
          <tr>
            <th>Date</th>
            <th>Time</th>
            <th>Court</th>
            <th>User Email</th>
            <th>Name</th>
            <th>Status</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody id="adminTableBody">
          <!-- Populated by JS -->
        </tbody>
      </table>
    </div>
  </div>

  <!-- Settings Tab -->
  <div class="admin-panel" id="tab-settings">
    <div class="settings-grid">

      <div class="settings-card">
        <h3 class="settings-title">GCash QR Code</h3>
        <p class="settings-desc">Upload a new QR code to replace the current payment QR displayed to users.</p>
        <div class="qr-preview-wrap" id="adminQrPreview">
          <img src="<?= $gcashQr ?>" alt="Current GCash QR" class="qr-img">
          <span class="qr-label">Current QR Code</span>
        </div>
        <form method="POST" enctype="multipart/form-data" class="settings-form">
          <label class="upload-label" for="new_gcash_qr">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" width="20"><polyline points="16 16 12 12 8 16"/><line x1="12" y1="12" x2="12" y2="21"/><path d="M20.39 18.39A5 5 0 0 0 18 9h-1.26A8 8 0 1 0 3 16.3"/></svg>
            Choose New QR Image
          </label>
          <input type="file" id="new_gcash_qr" name="new_gcash_qr" accept="image/*" class="hidden-file">
          <button type="submit" name="update_qr" class="btn-admin-save">Update QR Code</button>
        </form>
      </div>

      <div class="settings-card">
        <h3 class="settings-title">Court Availability</h3>
        <p class="settings-desc">Toggle court availability for maintenance or events.</p>
        <div class="court-toggles">
          <!-- Generated by JS -->
        </div>
      </div>

    </div>
  </div>

</div>

<!-- ===== BOOKING MODAL ===== -->
<div class="modal-overlay" id="bookingModal" role="dialog" aria-modal="true" aria-labelledby="modalTitle">
  <div class="modal-box">
    <button class="modal-close" id="modalClose" aria-label="Close">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" width="18"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>
    </button>

    <div class="modal-header">
      <span class="modal-badge">Confirm Reservation</span>
      <h2 class="modal-title" id="modalTitle">Booking Summary</h2>
    </div>

    <div class="modal-body">
      <!-- Summary -->
      <div class="booking-summary" id="bookingSummary"></div>

      <!-- GCash Section -->
      <div class="gcash-section">
        <div class="gcash-header">
          <span class="gcash-badge">GCash Payment</span>
        </div>
        <div class="gcash-body">
          <div class="qr-container">
            <img src="<?= $gcashQrModal ?>" alt="GCash QR Code" id="gcashQr" class="gcash-qr">
            <div class="gcash-info">
              <div class="gcash-number">09123-456-789</div>
              <div class="gcash-name">PicklePro Sports Hub</div>
              <div class="gcash-amount" id="gcashAmount">₱ 0.00</div>
            </div>
          </div>
        </div>
      </div>

      <!-- Receipt Upload -->
      <div class="upload-section">
        <label class="section-label">Upload GCash Receipt</label>
        <div class="upload-zone" id="uploadZone">
          <input type="file" id="payment_receipt" name="payment_receipt" accept="image/*" class="hidden-file">
          <div class="upload-placeholder" id="uploadPlaceholder">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" width="36"><polyline points="16 16 12 12 8 16"/><line x1="12" y1="12" x2="12" y2="21"/><path d="M20.39 18.39A5 5 0 0 0 18 9h-1.26A8 8 0 1 0 3 16.3"/></svg>
            <span>Click or drag receipt here</span>
            <span class="upload-hint">JPG, PNG, GIF up to 10MB</span>
          </div>
          <img id="receiptPreview" class="receipt-preview hidden" alt="Receipt preview">
        </div>
      </div>

      <!-- User Details Form -->
      <form method="POST" enctype="multipart/form-data" id="bookingForm">
        <input type="hidden" id="selected_slots" name="selected_slots">
        <input type="hidden" id="booking_date_field" name="booking_date">

        <div class="form-row">
          <div class="form-group">
            <label for="user_name">Full Name</label>
            <input type="text" id="user_name" name="user_name" placeholder="Juan dela Cruz" required autocomplete="name">
          </div>
          <div class="form-group">
            <label for="user_phone">Phone Number</label>
            <input type="tel" id="user_phone" name="user_phone" placeholder="09XX XXX XXXX" required autocomplete="tel">
          </div>
        </div>
        <div class="form-group">
          <label for="user_email">Email Address</label>
          <input type="email" id="user_email" name="user_email" placeholder="juan@email.com" required autocomplete="email">
        </div>

        <div class="modal-footer">
          <button type="button" class="btn-secondary" id="btnCancel">Cancel</button>
          <button type="submit" name="submit_booking" class="btn-primary">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" width="16"><polyline points="20 6 9 17 4 12"/></svg>
            Submit Booking
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

<!-- ===== RECEIPT MODAL (Admin) ===== -->
<div class="modal-overlay" id="receiptModal" role="dialog" aria-modal="true">
  <div class="modal-box modal-box--sm">
    <button class="modal-close" id="receiptModalClose">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" width="18"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>
    </button>
    <div class="modal-header">
      <span class="modal-badge">Admin View</span>
      <h2 class="modal-title">Payment Receipt</h2>
    </div>
    <div class="modal-body">
      <img id="receiptModalImg" src="" alt="Payment receipt" class="receipt-full">
      <div class="receipt-meta" id="receiptMeta"></div>
    </div>
  </div>
</div>

<!-- ===== TOAST ===== -->
<div class="toast" id="toast"></div>

<script src="app.js"></script>
</body>
</html>
